from . import ir_actions_report
from . import shipping_method_mixin
from . import stock_picking_package
from . import stock_picking
from . import delivery_carrier
from . import res_company
from . import res_config_settings
from . import shipping_account
from . import stock_move
from . import stock_package_type
from . import customs_documentation
